name: Put built files to release

on:
  release:
    types:
      - created
        
env:
  EXILED_REFERENCES_URL: https://misaka-zerotwo.github.io/SL-References/Dev.zip
  EXILED_REFERENCES: ${{ github.workspace }}/refs

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          vs-prerelease: false
          msbuild-architecture: x64
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES }} -Force
      - name: Restore packages
        run: nuget restore ${{ github.workspace }}/Timers.sln
      - name: Build RueI
        run: msbuild.exe ${{ github.workspace }}/Timers.sln /p:Configuration=RUEI /p:Platform="Any CPU"
      - name: Build HSM
        run: msbuild.exe ${{ github.workspace }}/Timers.sln /p:Configuration=HSM /p:Platform="Any CPU"
      - name: Rename RueI
        run: Rename-Item -Path ${{ github.workspace }/bin/RUEI/net48/Timers.dll -NewName "Timers-RueI.dll"
      - name: Rename HSM
        run: Rename-Item -Path ${{ github.workspace }/bin/HSM/net48/Timers.dll -NewName "Timers-HSM.dll"
      - name: Add RueI dll to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/bin/RUEI/net48/Timers-RueI.dll
          asset_name: Timers-RueI.dll
      - name: Add HSM dll to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/bin/HSM/net48/Timers-HSM.dll
          asset_name: Timers-HSM.dll